apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-server-deployment
spec:
  selector:
    matchLabels:
      app: cache-server
  template:
    metadata:
      labels:
        app: cache-server
    spec:
      containers:
        - name: cache-server
          image: ghcr.io/wlun001/cache-server:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
`---
apiVersion: v1
kind: Service
metadata:
  name: cache-server-service
  annotations:
    cloud.google.com/backend-config: '{"ports": {"3000":"basic-backendconfig"}}'
spec:
  type: NodePort
  selector:
    app: cache-server
  ports:
    - port: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  defaultBackend:
    service:
      name: cache-server-service
      port:
        number: 3000
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: basic-backendconfig
spec:
  cdn:
    enabled: true



