apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache-server-deployment
spec:
  selector:
    matchLabels:
      app: cache-server
  template:
    metadata:
      labels:
        app: cache-server
    spec:
      containers:
        - name: cache-server
          image: ghcr.io/wlun001/cache-server:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: cache-server-service
spec:
  type: LoadBalancer
  selector:
    app: cache-server
  ports:
    - port: 3000

