version: '3'
services:
  mongodb:
    build:
      context: .
      dockerfile: mongo.Dockerfile
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=apple123
      - MONGO_INITDB_DATABASE=store
    volumes:
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js
