apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: kaniko-pipeline-auth
spec:
  workspaces:
    - name: git-source
    - name: ssh-creds
    - name: dockerconfig
  params:
    - name: git_revision
  tasks:
    - name: fetch-from-git
      taskRef:
        name: git-clone
      params:
        - name: url
          value: git@github.com:WLun001/cncf-demo.git
        - name: revision
          value: $(params.git_revision)
      workspaces:
        - name: output
          workspace: git-source
        - name: ssh-directory
          workspace: ssh-creds
    #    - name: ls-dir
    #      runAfter: [ fetch-from-git ]
    #      taskRef:
    #        name: bash
    #      params:
    #        - name: args
    #          value: ls -la
    #      workspaces:
    #        - name: source
    #          workspace: git-source
    - name: build-image
      runAfter: [ fetch-from-git ]
      taskRef:
        name: kaniko
      params:
        - name: IMAGE
          value: ghcr.io/wlun001/hello-world
        - name: CONTEXT
          value: examples/hello-world
        - name: DOCKERFILE
          value: $(workspaces.source.path)/examples/hello-world/Dockerfile
      workspaces:
        - name: source
          workspace: git-source
        - name: dockerconfig
          workspace: dockerconfig
