kind: Secret
apiVersion: v1
metadata:
  name: ssh-credentials
type: Opaque
stringData:
  # ssh-keygen -t ed25519 -C "example.com"
  # cat id_ed25519
  id_ed25519: |
    XXXXXX
  #  ssh-keyscan github.com >> githubKey
  # cat githubkey
  known_hosts: |
    XXXXX

  config: |
    IdentityFile ~/.ssh/id_ed25519
